### ISSUE TITLE
Problem with loading new project link

### ISSUE THREAD

**Issue by itailiors** [block-core/angor-hub-old#43]
whenever I go directly to the project link on the hub ( " https://hub.angor.io/profile/f75e8fb9ac1d1d2249b7a679536ef58397d00f77c221052b9360f418c024203c " )
I get this - 
![image](https://github.com/user-attachments/assets/d67961af-0b62-4766-8888-6aed1a3acba0)

and if i refresh i get the same thing,
Then if i go to the explorer, and back to the link, it does find the project.

Seems like when you go directly to the project link, we aren't searching the relay for the info.

**Comment by dangershony** [comment]
Was this fixed?
